const ar: Record<string, string> = {
  'advances.report.title': 'تقرير سلف الموظف',
  'advances.report.salary': 'الراتب',
  'advances.report.totalAdvances': 'إجمالي السلف',
  'advances.report.remaining': 'المتبقي',
  'advances.report.generated': 'تم الإنشاء في',
  'advances.report.print': 'طباعة',
  'advances.report.noAdvances': 'لا توجد سلف لهذا الموظف',
  'advances.form.employee': 'اسم الموظف',
  'advances.col.amount': 'المبلغ',
  'advances.col.date': 'التاريخ',
  'advances.col.specialty': 'التخصص',
  'advances.col.notes': 'ملاحظات',
  'coverages.report.title': 'تقرير التغطيات',
  'coverages.report.totalCoverages': 'عدد التغطيات',
  'coverages.report.totalPrice': 'إجمالي المبلغ',
  'coverages.report.totalShare': 'إجمالي النسب',
  'coverages.report.noCoverages': 'لا توجد تغطيات لهذا الموظف',
  'coverages.form.name': 'الموظف',
  'coverages.col.sessionType': 'نوع الجلسة',
  'coverages.col.price': 'المبلغ',
  'coverages.col.therapistShare': 'نسبة المعالج',
  'coverages.col.date': 'التاريخ',
  'coverages.col.from': 'من',
  'coverages.col.to': 'إلى',
  'coverages.sessionType.normal': 'عادية',
  'coverages.sessionType.hijama': 'حجامة',
  'patients.download.title': 'استمارة التقييم العام',
  'patients.download.diagnosis': 'التشخيص',
  'patients.download.history': 'التاريخ المرضي',
  'patients.download.chiefComplaint': 'الشكوى الرئيسية',
  'patients.download.notes': 'ملاحظات',
  'patients.download.treatmentPlan': 'خطة العلاج',
  'patients.download.doctorSignature': 'توقيع الطبيب',
  'patients.download.print': 'طباعة',
  'patients.add.form.name': 'الاسم',
  'patients.add.form.gender': 'الجنس',
  'patients.add.form.age': 'العمر',
  'patients.add.form.date': 'التاريخ',
  'patients.col.phone': 'الهاتف',
  'patients.add.form.examType': 'نوع الفحص',
  'patients.col.serial': 'الرقم',
  'patients.add.form.price': 'السعر',
  'patients.download.generated': 'تم الإنشاء في',
  'patients.add.form.gender.male': 'ذكر',
  'patients.add.form.gender.female': 'أنثى',
  'patients.add.form.examType.physiotherapy': 'علاج طبيعي',
  'patients.add.form.examType.nutrition': 'تغذية',
};

const en: Record<string, string> = {
  'advances.report.title': 'Employee Salary Report',
  'advances.report.salary': 'Salary',
  'advances.report.totalAdvances': 'Total Advances',
  'advances.report.remaining': 'Remaining',
  'advances.report.generated': 'Generated on',
  'advances.report.print': 'Print',
  'advances.report.noAdvances': 'No advances for this employee',
  'advances.form.employee': 'Employee Name',
  'advances.col.amount': 'Amount',
  'advances.col.date': 'Date',
  'advances.col.specialty': 'Specialty',
  'advances.col.notes': 'Notes',
  'coverages.report.title': 'Coverages Report',
  'coverages.report.totalCoverages': 'Total Coverages',
  'coverages.report.totalPrice': 'Total Price',
  'coverages.report.totalShare': 'Total Shares',
  'coverages.report.noCoverages': 'No coverages for this employee',
  'coverages.form.name': 'Employee',
  'coverages.col.sessionType': 'Session Type',
  'coverages.col.price': 'Price',
  'coverages.col.therapistShare': 'Therapist Share',
  'coverages.col.date': 'Date',
  'coverages.col.from': 'From',
  'coverages.col.to': 'To',
  'coverages.sessionType.normal': 'Normal',
  'coverages.sessionType.hijama': 'Hijama',
  'patients.download.title': 'General Assessment Form',
  'patients.download.diagnosis': 'Diagnosis',
  'patients.download.history': 'History',
  'patients.download.chiefComplaint': 'Chief Complaint',
  'patients.download.notes': 'Notes',
  'patients.download.treatmentPlan': 'Treatment Plan',
  'patients.download.doctorSignature': 'Doctor Signature',
  'patients.download.print': 'Print',
  'patients.add.form.name': 'Name',
  'patients.add.form.gender': 'Gender',
  'patients.add.form.age': 'Age',
  'patients.add.form.date': 'Date',
  'patients.col.phone': 'Phone',
  'patients.add.form.examType': 'Exam Type',
  'patients.col.serial': '#',
  'patients.add.form.price': 'Price',
  'patients.download.generated': 'Generated on',
  'patients.add.form.gender.male': 'Male',
  'patients.add.form.gender.female': 'Female',
  'patients.add.form.examType.physiotherapy': 'Physiotherapy',
  'patients.add.form.examType.nutrition': 'Nutrition',
};

const locales: Record<string, Record<string, string>> = { ar, en };

export function t(key: string, lang: string = 'en', ...args: string[]): string {
  const label = locales[lang]?.[key] ?? locales['en']?.[key] ?? key;
  return args.length > 0 ? label.replace(/%s/g, () => args.shift() || '') : label;
}
